/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIGeshabitat;

import BLGeshabitat.Anexo;
import BLGeshabitat.Candidatura;
import BLGeshabitat.Familiar;
import BLGeshabitat.Funcionario;
import DAOGeshabitat.PersistableException;
import java.awt.Component;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nelson
 */
public class JintFrmNewCand extends javax.swing.JInternalFrame  {
    
    private Candidatura cand;


    /**
     * Creates new form JintFrmNewCand
     */
    public JintFrmNewCand() {
        initComponents();
         try {
            List<Object> funcionarios = JmdiMain.facadeBL.getAll(new Funcionario());
            for(Object obj : funcionarios) {
                jCmbFuncionario.addItem((Funcionario)obj);
            }
        } catch (PersistableException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Erro", JOptionPane.ERROR_MESSAGE);
        }       
    }
    
        
    
    public JintFrmNewCand(Candidatura cand) {
        initComponents();

        try {
            this.OpenCand(cand);
        } catch (PersistableException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Erro", JOptionPane.ERROR_MESSAGE);
        }
        this.cand= cand;
        this.jBtAddFamiliar.setEnabled(false);
        this.jBtAddCand.setVisible(false);
        this.jBtProcurarAnexo.setEnabled(false);
        this.jBtRemoveAgregado.setEnabled(false);
        this.jBtRemoverAnexo.setEnabled(false);
    }
    
           


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelInfoCand = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtNif = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCmbEscolaridade = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jCmbEstadoCivil = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtProfissao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtTelemovel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtTelefone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtRua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtCp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtLocalidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtRendimento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTxtPrestacao = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jCmbFuncionario = new javax.swing.JComboBox();
        jDpDtNascimento = new org.jdesktop.swingx.JXDatePicker();
        jBtSair = new javax.swing.JButton();
        jBtAddCand = new javax.swing.JButton();
        jPanelAnexos = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jBtProcurarAnexo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblAnexos = new javax.swing.JTable();
        jBtRemoverAnexo = new javax.swing.JButton();
        jTxtDescricao = new javax.swing.JTextField();
        jBtAbrir = new javax.swing.JButton();
        jPanelInfoAgregado = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTxtNomeAgr = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jCmbEscolaridadeAgr = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jCmbEstadoAgr = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTxtOcupacaoAgr = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jCmbParentesco = new javax.swing.JComboBox();
        jBtAddFamiliar = new javax.swing.JButton();
        jBtRemoveAgregado = new javax.swing.JButton();
        jScrollPaneAgregado = new javax.swing.JScrollPane();
        jTblAgregado = new javax.swing.JTable();
        jDpDtNascimentoAgr = new org.jdesktop.swingx.JXDatePicker();

        setClosable(true);
        setIconifiable(true);
        setTitle("Nova Candidatura");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPanelInfoCand.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Informacao Candidato"));

        jLabel1.setText("Nome Completo:");

        jLabel2.setText("Contribuinte:");

        jLabel3.setText("Escolaridade:");

        jCmbEscolaridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ensino Superior", "Ensino Secundário", "1º Ciclo" }));

        jLabel4.setText("Estado Civil:");

        jCmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado ", "Viuvo" }));

        jLabel5.setText("Data Nascimento:");

        jLabel6.setText("Profissao:");

        jLabel7.setText("Telemóvel:");

        jLabel8.setText("Telefone Fixo:");

        jLabel9.setText("Rua:");

        jLabel10.setText("Cod. Postal:");

        jLabel11.setText("Localidade:");

        jLabel13.setText("Email:");

        jLabel14.setText("Rendimento Anual Bruto:");

        jLabel15.setText("€");

        jLabel16.setText("Prestação:");

        jLabel17.setText("€");

        jLabel26.setText("Responsavel:");

        DateFormat dateFormat = DateFormat.getDateInstance(DateFormat.LONG, Locale.forLanguageTag("pt"));
        jDpDtNascimento.setFormats(dateFormat);

        jDpDtNascimento.setDate(new Date());

        javax.swing.GroupLayout jPanelInfoCandLayout = new javax.swing.GroupLayout(jPanelInfoCand);
        jPanelInfoCand.setLayout(jPanelInfoCandLayout);
        jPanelInfoCandLayout.setHorizontalGroup(
            jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNif, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                        .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDpDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtPrestacao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17))
                                    .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtTelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtCp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                        .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jTxtEmail))
                                    .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(280, 280, 280))))
        );
        jPanelInfoCandLayout.setVerticalGroup(
            jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoCandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jCmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCmbEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jCmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jDpDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtTelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTxtLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTxtRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jTxtPrestacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        jBtSair.setText("Sair");
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        jBtAddCand.setText("Adicionar");
        jBtAddCand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAddCandActionPerformed(evt);
            }
        });

        jPanelAnexos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Anexos"));

        jLabel25.setText("Descricao:");

        jBtProcurarAnexo.setText("Anexar");
        jBtProcurarAnexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtProcurarAnexoActionPerformed(evt);
            }
        });

        jTblAnexos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descricao", "Caminho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblAnexos.setColumnSelectionAllowed(true);
        jTblAnexos.getTableHeader().setReorderingAllowed(false);
        jTblAnexos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblAnexosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTblAnexos);
        jTblAnexos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTblAnexos.getColumnModel().getColumnCount() > 0) {
            jTblAnexos.getColumnModel().getColumn(0).setMinWidth(70);
            jTblAnexos.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTblAnexos.getColumnModel().getColumn(0).setMaxWidth(100);
            jTblAnexos.getColumnModel().getColumn(1).setMinWidth(300);
            jTblAnexos.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTblAnexos.getColumnModel().getColumn(1).setMaxWidth(400);
        }

        jBtRemoverAnexo.setText("Remover");
        jBtRemoverAnexo.setEnabled(false);
        jBtRemoverAnexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRemoverAnexoActionPerformed(evt);
            }
        });

        jBtAbrir.setText("Abrir Anexo");
        jBtAbrir.setEnabled(false);
        jBtAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAnexosLayout = new javax.swing.GroupLayout(jPanelAnexos);
        jPanelAnexos.setLayout(jPanelAnexosLayout);
        jPanelAnexosLayout.setHorizontalGroup(
            jPanelAnexosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnexosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAnexosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelAnexosLayout.createSequentialGroup()
                        .addGroup(jPanelAnexosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAnexosLayout.createSequentialGroup()
                                .addComponent(jBtRemoverAnexo)
                                .addGap(18, 18, 18)
                                .addComponent(jBtAbrir))
                            .addGroup(jPanelAnexosLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtProcurarAnexo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAnexosLayout.setVerticalGroup(
            jPanelAnexosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnexosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelAnexosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jBtProcurarAnexo)
                    .addComponent(jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAnexosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtRemoverAnexo)
                    .addComponent(jBtAbrir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelInfoAgregado.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Agregado Familiar"));

        jLabel18.setText("Nome Completo:");

        jLabel19.setText("Escolaridade:");

        jCmbEscolaridadeAgr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Desconhecido", "Ensino Superior", "Ensino Secundário", "1º Ciclo" }));

        jLabel20.setText("Estado Civil:");

        jCmbEstadoAgr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Desconhecido", "Solteiro", "Casado ", "Viuvo" }));

        jLabel21.setText("Data Nascimento:");

        jLabel22.setText("Ocupação:");

        jLabel23.setText("Parentesco:");

        jCmbParentesco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Desconhecido", "Filho", "Pai", "Tio", "Sobrinho" }));

        jBtAddFamiliar.setText("Adicionar");
        jBtAddFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAddFamiliarActionPerformed(evt);
            }
        });

        jBtRemoveAgregado.setText("Remover");
        jBtRemoveAgregado.setEnabled(false);
        jBtRemoveAgregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRemoveAgregadoActionPerformed(evt);
            }
        });

        jTblAgregado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Parentesco", "Estado Civil", "Escolaridade", "Dt. Nascimento", "Ocupação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTblAgregado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblAgregadoMouseClicked(evt);
            }
        });
        jScrollPaneAgregado.setViewportView(jTblAgregado);

        jDpDtNascimentoAgr.setFormats(dateFormat);

        jDpDtNascimentoAgr.setDate(new Date());

        javax.swing.GroupLayout jPanelInfoAgregadoLayout = new javax.swing.GroupLayout(jPanelInfoAgregado);
        jPanelInfoAgregado.setLayout(jPanelInfoAgregadoLayout);
        jPanelInfoAgregadoLayout.setHorizontalGroup(
            jPanelInfoAgregadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoAgregadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoAgregadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoAgregadoLayout.createSequentialGroup()
                        .addComponent(jBtAddFamiliar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtRemoveAgregado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelInfoAgregadoLayout.createSequentialGroup()
                        .addGroup(jPanelInfoAgregadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneAgregado)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoAgregadoLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNomeAgr)
                                .addGap(260, 260, 260))
                            .addGroup(jPanelInfoAgregadoLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtOcupacaoAgr, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelInfoAgregadoLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbEscolaridadeAgr, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbEstadoAgr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDpDtNascimentoAgr, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanelInfoAgregadoLayout.setVerticalGroup(
            jPanelInfoAgregadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoAgregadoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelInfoAgregadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTxtNomeAgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoAgregadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jCmbEscolaridadeAgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbEstadoAgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jDpDtNascimentoAgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoAgregadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTxtOcupacaoAgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jCmbParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoAgregadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtRemoveAgregado)
                    .addComponent(jBtAddFamiliar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneAgregado, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAnexos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtAddCand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelInfoCand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelInfoAgregado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInfoCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelInfoAgregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAnexos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtAddCand)
                    .addComponent(jBtSair))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Candidatura getCand() {
        return cand;
    }
    public void setCand(Candidatura cand) {
        this.cand = cand;
    }
    
    
    
    private void OpenCand(Candidatura cand) throws PersistableException {
        this.jCmbFuncionario.addItem((Funcionario)JmdiMain.facadeBL.get(new Funcionario(), cand.getFuncionario_Id()));
        
        this.jTxtNome.setText(cand.getNome());
        this.jTxtNif.setText(String.valueOf(cand.getNif()));
        this.jDpDtNascimento.setDate(cand.getDtNascimento());
        this.jCmbEscolaridade.addItem(cand.getEscolaridade());
        this.jCmbEstadoCivil.addItem(cand.getEstadoCivil());
        this.jTxtProfissao.setText(cand.getProfissao());
        this.jTxtTelemovel.setText(cand.getTelemovel());
        this.jTxtTelefone.setText(cand.getTelefone());
        this.jTxtRua.setText(cand.getRua());
        this.jTxtCp.setText(cand.getCp());
        this.jTxtLocalidade.setText(cand.getLocalidade());
        this.jTxtEmail.setText(cand.getEmail());
        this.jTxtRendimento.setText(String.valueOf(cand.getRendimento()));
        this.jTxtPrestacao.setText(String.valueOf(cand.getPrestacao()));
        
        for(Familiar f : cand.getAgregado()) {
            Object obj[] = {f.getId(),f.getNome(),f.getGrau(),f.getEstadoCivil(),f.getEscolaridade(), f.getDtNascimento(), f.getOcupacao()};
             ((DefaultTableModel)this.jTblAgregado.getModel()).addRow(obj);
        }
        
        for(Anexo a : cand.getAnexos()) {
            Object obj[] = {a.getId(),a.getDescricao(),a.getCaminho()}; 
            ((DefaultTableModel)this.jTblAnexos.getModel()).addRow(obj);
        }
     }
    
    private void populateCmbFuncionario() {
        try {
            List<Object> funcionarios = JmdiMain.facadeBL.getAll(new Funcionario());
            for(Object obj : funcionarios) {
                jCmbFuncionario.addItem((Funcionario)obj);
            }
        } catch (PersistableException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jBtAddFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAddFamiliarActionPerformed
        if(jTxtNomeAgr.getText().equals("")) {
            JOptionPane.showMessageDialog(this,"Tem de preencher os campos obrigatorios!","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int Id = this.jTblAgregado.getRowCount()+1;
        String Nome = this.jTxtNomeAgr.getText();
        String EstadoCivil = this.jCmbEstadoAgr.getSelectedItem().toString();
        Date DtNascimento = this.jDpDtNascimentoAgr.getDate();
        String Ocupacao = this.jTxtOcupacaoAgr.getText();
        String Parentesco = this.jCmbParentesco.getSelectedItem().toString();
        String Escolaridade = this.jCmbEscolaridadeAgr.getSelectedItem().toString();
        Familiar familiar = new Familiar(Id,Nome,EstadoCivil,DtNascimento,Escolaridade,Ocupacao,Parentesco);
        
        ((DefaultTableModel)this.jTblAgregado.getModel()).addRow(familiar.getRowData());
        
    }//GEN-LAST:event_jBtAddFamiliarActionPerformed

    private void jBtProcurarAnexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtProcurarAnexoActionPerformed

        if(this.jTxtDescricao.getText().equals("")) {
            JOptionPane.showMessageDialog(this,"Por favor insira uma descrição do ficheiro a anexar!","Erro", JOptionPane.ERROR_MESSAGE);
            return;    
        }
        JFileChooser chooser = new JFileChooser();
        chooser.setAcceptAllFileFilterUsed(true);        
    
        int returnVal = chooser.showOpenDialog(this);
    
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            String filename = chooser.getSelectedFile().getAbsoluteFile().getAbsolutePath();
            ((DefaultTableModel)this.jTblAnexos.getModel()).addRow(new Object[] { this.jTblAnexos.getRowCount()+1,jTxtDescricao.getText(),filename });
        }
        
               
    }//GEN-LAST:event_jBtProcurarAnexoActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void jTblAgregadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblAgregadoMouseClicked
        int row = jTblAgregado.getSelectedRow();
        if(row!=-1) this.jBtRemoveAgregado.setEnabled(true);
        else this.jBtRemoveAgregado.setEnabled(false);
    }//GEN-LAST:event_jTblAgregadoMouseClicked

    private void jBtRemoveAgregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRemoveAgregadoActionPerformed
        int row = jTblAgregado.getSelectedRow();  
        ((DefaultTableModel)this.jTblAgregado.getModel()).removeRow(row);
        JmdiMain.reorderId(((DefaultTableModel)this.jTblAgregado.getModel()));
        this.jBtRemoveAgregado.setEnabled(false);
        
    }//GEN-LAST:event_jBtRemoveAgregadoActionPerformed

    private void jTblAnexosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblAnexosMouseClicked
        int row = jTblAnexos.getSelectedRow();
        if(row!=-1)  {
            this.jBtRemoverAnexo.setEnabled(true);
            this.jBtAbrir.setEnabled(true);
        }
        else  {
            this.jBtRemoverAnexo.setEnabled(false);

        }
    }//GEN-LAST:event_jTblAnexosMouseClicked

    private void jBtRemoverAnexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRemoverAnexoActionPerformed
        int row = jTblAnexos.getSelectedRow();  
        ((DefaultTableModel)this.jTblAnexos.getModel()).removeRow(row);
        JmdiMain.reorderId(((DefaultTableModel)this.jTblAnexos.getModel()));
        this.jBtRemoverAnexo.setEnabled(false);
        this.jBtAbrir.setEnabled(false);
    }//GEN-LAST:event_jBtRemoverAnexoActionPerformed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtSairActionPerformed

    private void jBtAddCandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAddCandActionPerformed
        int Id = -1;
        int Nif;
        try{
            Nif = Integer.valueOf(jTxtNif.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,"O número de contribuinte que inseriu não é válido","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String Nome = jTxtNome.getText();
        String Telefone = jTxtTelefone.getText();
        String Email = jTxtEmail.getText();
        String Rua = jTxtRua.getText();
        String Localidade = jTxtLocalidade.getText();
        String Cp = jTxtCp.getText();
        Date DtNascimento = jDpDtNascimento.getDate();
        String Profissao = jTxtProfissao.getText();
        String Estado = "Em Aprovação";
        String Escolaridade = (String)jCmbEscolaridade.getSelectedItem();
        String EstadoCivil = (String)jCmbEstadoCivil.getSelectedItem();
        String Telemovel = jTxtTelemovel.getText();
        
        float Rendimento=0;
        float Prestacao=0;
        try{
            if(!"".equals(jTxtRendimento.getText()))
            Rendimento = Float.valueOf(jTxtRendimento.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,"O valor referente ao Rendimento que inseriu não é válido","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            if(!"".equals(jTxtPrestacao.getText()))
            Prestacao = Float.valueOf(jTxtPrestacao.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,"O valor referente à Prestacao que inseriu não é válido","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int Funcionario_Id = -1;
        if(jCmbFuncionario.getSelectedItem()!=null) {
            Funcionario func =(Funcionario)jCmbFuncionario.getSelectedItem(); 
            Funcionario_Id=func.getId();
        }
        Candidatura candidatura = new Candidatura(Nif, Nome, Telefone, Email, Rua, Localidade, Cp, new java.sql.Date(DtNascimento.getTime()),  Profissao, Rendimento, 
                                                  Estado, Escolaridade, Funcionario_Id, Prestacao, EstadoCivil, Telemovel);
        
        candidatura.setAgregado(getFamiliares(jTblAgregado));
        candidatura.setAnexos(getAnexos(jTblAnexos));
        this.cand=candidatura;
        
        try {
            JmdiMain.facadeBL.put(candidatura);
        } catch (PersistableException ex) {
            JOptionPane.showMessageDialog(this,"Não foi possivel guardar a candidatura com sucesso!\n"+ex.getMessage(),"Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this,"Registo adicionado com sucesso!","Sucesso", JOptionPane.INFORMATION_MESSAGE);

        this.dispose();
        
    }//GEN-LAST:event_jBtAddCandActionPerformed

    private void jBtAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAbrirActionPerformed
        int row = jTblAnexos.getSelectedRow();  
        File path = new File((String)(this.jTblAnexos.getValueAt(row, 2)));
        Desktop dt = Desktop.getDesktop();
        try {
            dt.open(path);
        } catch (IOException ex) {
            Logger.getLogger(JintFrmNewCand.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtAbrirActionPerformed

    
    private List<Familiar> getFamiliares(JTable table) {
        int Id;
        String Nome;
        String Parentesco;
        String EstadoCivil;
        String Escolaridade;
        Date DtNascimento;
        String Ocupacao;
                
        ArrayList<Familiar> ret = new ArrayList<>();
        for(int i=0; i<table.getRowCount();i++) {
                Id=(int)table.getValueAt(i, 0);
                Nome=(String)table.getValueAt(i, 1).toString();
                Parentesco=(String)table.getValueAt(i, 2).toString();
                EstadoCivil=(String)table.getValueAt(i, 3).toString();
                Escolaridade=(String)table.getValueAt(i, 4).toString();
                DtNascimento = (Date)table.getValueAt(i, 5);                            
                Ocupacao=(String)table.getValueAt(i, 6).toString();
                
                ret.add(new Familiar(Id,Nome,EstadoCivil,DtNascimento,Escolaridade,Ocupacao,Parentesco));
        } 
        return ret;
    }
    
    
    private List<Anexo> getAnexos(JTable table) {
        int Id;
        String Descricao;
        String Caminho;
                
        ArrayList<Anexo> ret = new ArrayList<>();
        for(int i=0; i<table.getRowCount();i++) {
                Id=(int)table.getValueAt(i, 0);
                Descricao=(String)table.getValueAt(i, 1);
                Caminho=(String)table.getValueAt(i, 2);

                ret.add(new Anexo(Id,Descricao,Caminho));
        } 
        return ret;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAbrir;
    private javax.swing.JButton jBtAddCand;
    private javax.swing.JButton jBtAddFamiliar;
    private javax.swing.JButton jBtProcurarAnexo;
    private javax.swing.JButton jBtRemoveAgregado;
    private javax.swing.JButton jBtRemoverAnexo;
    private javax.swing.JButton jBtSair;
    private javax.swing.JComboBox jCmbEscolaridade;
    private javax.swing.JComboBox jCmbEscolaridadeAgr;
    private javax.swing.JComboBox jCmbEstadoAgr;
    private javax.swing.JComboBox jCmbEstadoCivil;
    private javax.swing.JComboBox jCmbFuncionario;
    private javax.swing.JComboBox jCmbParentesco;
    private org.jdesktop.swingx.JXDatePicker jDpDtNascimento;
    private org.jdesktop.swingx.JXDatePicker jDpDtNascimentoAgr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAnexos;
    private javax.swing.JPanel jPanelInfoAgregado;
    private javax.swing.JPanel jPanelInfoCand;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneAgregado;
    private javax.swing.JTable jTblAgregado;
    private javax.swing.JTable jTblAnexos;
    private javax.swing.JTextField jTxtCp;
    private javax.swing.JTextField jTxtDescricao;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtLocalidade;
    private javax.swing.JTextField jTxtNif;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtNomeAgr;
    private javax.swing.JTextField jTxtOcupacaoAgr;
    private javax.swing.JTextField jTxtPrestacao;
    private javax.swing.JTextField jTxtProfissao;
    private javax.swing.JTextField jTxtRendimento;
    private javax.swing.JTextField jTxtRua;
    private javax.swing.JTextField jTxtTelefone;
    private javax.swing.JTextField jTxtTelemovel;
    // End of variables declaration//GEN-END:variables

}