/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIGeshabitat;

import BLGeshabitat.Utilizadores.Funcionario;
import BLGeshabitat.Projectos.Projecto;
import BLGeshabitat.Fundos.RegistoVoluntariado;
import BLGeshabitat.Projectos.Tarefa;
import BLGeshabitat.Fundos.Voluntario;
import DAOGeshabitat.PersistableException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author 
 */
public class JintFrmAlocarVoluntarios extends ModalJinternalFrame  {
    private int Project_Id;
    /**
     * Creates new form JintFrmAlocarVoluntarios
     */
    public JintFrmAlocarVoluntarios(int Project_Id) {
        this.Project_Id=Project_Id;
        
        initComponents();
        try {
            this.fillInfo();
        } catch (PersistableException ex) {
            Logger.getLogger(JintFrmAlocarVoluntarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblVoluntarios = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblSelecao = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCmbResponsavel = new javax.swing.JComboBox();
        jTxtEquipa = new javax.swing.JTextField();
        jBtCancelar = new javax.swing.JButton();
        jCmbTarefas = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtTempo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Registar voluntariado");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Registar Voluntariado"));

        jLabel3.setText("Responsavel:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Selecção de Voluntarios"));

        jTblVoluntarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Localidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblVoluntarios.getTableHeader().setReorderingAllowed(false);
        jTblVoluntarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblVoluntariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTblVoluntarios);
        jTblVoluntarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTblVoluntarios.getColumnModel().getColumnCount() > 0) {
            jTblVoluntarios.getColumnModel().getColumn(0).setMinWidth(70);
            jTblVoluntarios.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTblVoluntarios.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        jTblSelecao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Localidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblSelecao.setColumnSelectionAllowed(true);
        jTblSelecao.getTableHeader().setReorderingAllowed(false);
        jTblSelecao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblSelecaoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTblSelecao);
        jTblSelecao.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTblSelecao.getColumnModel().getColumnCount() > 0) {
            jTblSelecao.getColumnModel().getColumn(0).setMinWidth(70);
            jTblSelecao.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTblSelecao.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        jLabel1.setText("Todos Voluntarios");

        jLabel2.setText("Voluntarios selecionados:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jBtGuardar.setText("Registar");
        jBtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGuardarActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome equipa:");

        jBtCancelar.setText("Cancelar");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Tarefa:");

        jLabel7.setText("Tempo:");

        jTxtTempo.setText("1");

        jLabel8.setText("(dias)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtCancelar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCmbResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEquipa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCmbTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCmbResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(jTxtEquipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTxtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jBtGuardar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtCancelar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void fillInfo() throws PersistableException {
        List<Tarefa> tarefas = JmdiMain.facadeBL.getTarefasIniciadas(Project_Id);
        for(Tarefa tar :  tarefas) {
            this.jCmbTarefas.addItem(tar);
        }
        
        List<Object> funcionarios = JmdiMain.facadeBL.getAll(new Funcionario());
        for(Object obj :  funcionarios) {
            this.jCmbResponsavel.addItem((Funcionario)obj);
        }
        
        
        DefaultTableModel tableModel = (DefaultTableModel)jTblVoluntarios.getModel();

        List<Object> voluntarios = JmdiMain.facadeBL.getAll(new Voluntario());
        for(Object obj : voluntarios) {
            Voluntario v = (Voluntario)obj;
            tableModel.addRow(new Object[]{v.getId(),v.getNome(),v.getLocalidade()});
            
        }
        
    }
    
    private void jBtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGuardarActionPerformed
        int Tarefa_Id = ((Tarefa)(this.jCmbTarefas.getSelectedItem())).getId();
        int Funcionario_Id = ((Funcionario)(this.jCmbResponsavel.getSelectedItem())).getId();
        float Tempo=-1;
        try {
            Tempo = Float.valueOf(jTxtTempo.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,"O valor que inseriu para o tempo de trabalho é inválido!","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String Equipa = jTxtEquipa.getText();
        List<Integer> voluntarios = new ArrayList();
        
        for(int i=0;i<this.jTblSelecao.getRowCount();i++) {
           int voluntarios_id = (Integer)this.jTblSelecao.getValueAt(i,0);
           RegistoVoluntariado registo = new RegistoVoluntariado(Tarefa_Id,Tempo,Funcionario_Id,Equipa,voluntarios_id); 
           try {
               JmdiMain.facadeBL.put(registo);
           } catch (PersistableException ex) {
               JOptionPane.showMessageDialog(this,"Ocorreu um erro ao gravar o registo!","Erro", JOptionPane.ERROR_MESSAGE);
           }
        }
        JOptionPane.showMessageDialog(this,"Registo adicionado com sucesso!","Sucesso", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        
    }//GEN-LAST:event_jBtGuardarActionPerformed

    private void jTblVoluntariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblVoluntariosMouseClicked
        int row = this.jTblVoluntarios.getSelectedRow();
        DefaultTableModel tableModelVoluntarios  = (DefaultTableModel)jTblVoluntarios.getModel();
        DefaultTableModel tableModelSelecao = (DefaultTableModel)jTblSelecao.getModel();
        
        Object obj[] = {tableModelVoluntarios.getValueAt(row, 0), tableModelVoluntarios.getValueAt(row, 1), tableModelVoluntarios.getValueAt(row, 2)};
        tableModelSelecao.addRow(obj);

    }//GEN-LAST:event_jTblVoluntariosMouseClicked

    private void jTblSelecaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblSelecaoMouseClicked
        int row = this.jTblSelecao.getSelectedRow();
        DefaultTableModel tableModelSelecao = (DefaultTableModel)jTblSelecao.getModel();
        tableModelSelecao.removeRow(row);
    }//GEN-LAST:event_jTblSelecaoMouseClicked




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtGuardar;
    private javax.swing.JComboBox jCmbResponsavel;
    private javax.swing.JComboBox jCmbTarefas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTblSelecao;
    private javax.swing.JTable jTblVoluntarios;
    private javax.swing.JTextField jTxtEquipa;
    private javax.swing.JTextField jTxtTempo;
    // End of variables declaration//GEN-END:variables

}
