/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIGeshabitat;

import BLGeshabitat.Projectos.Fase;
import BLGeshabitat.Projectos.Tarefa;
import DAOGeshabitat.PersistableException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author 
 */
public class JintFrmGerirFases extends ModalJinternalFrame  {
    private int Project_Id;

    /**
     * Creates new form JintFrmFases
     * @param Project_Id
     */
    public JintFrmGerirFases(int Project_Id) {
        this.Project_Id = Project_Id;
        initComponents();
        this.LoadFases();
    }

    
    public void LoadFases() {
        try {
            List<Object> fases = JmdiMain.facadeBL.getAll(new Fase(),"Projecto_Id",String.valueOf(this.Project_Id));
            DefaultListModel listmodel = (DefaultListModel) jLstFases.getModel();
            listmodel.clear();
            for(Object obj : fases) {
                Fase f = (Fase)obj;
                listmodel. addElement(f);
            }
        } catch (PersistableException ex) {
            JOptionPane.showMessageDialog(this,"Ocorreu um erro ao carregar as fases do projecto","Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLstFases = new javax.swing.JList(new DefaultListModel());
        jScrollPane3 = new javax.swing.JScrollPane();
        jLstTarefas = new javax.swing.JList(new DefaultListModel());
        jLabel17 = new javax.swing.JLabel();
        jTxtDescricao = new javax.swing.JTextField();
        jBtAdicionarFase = new javax.swing.JButton();
        jBtRemoverFase = new javax.swing.JButton();
        jBtAddTarefa = new javax.swing.JButton();
        jBtRemoveTarefa = new javax.swing.JButton();
        jBtCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gestão de tarefas");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Gestão de Fases/Tarefas"));

        jSplitPane1.setDividerLocation(300);

        jLstFases.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLstFases.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLstFasesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jLstFases);

        jSplitPane1.setLeftComponent(jScrollPane2);

        jScrollPane3.setViewportView(jLstTarefas);

        jSplitPane1.setRightComponent(jScrollPane3);

        jLabel17.setText("Descrição fase:");

        jBtAdicionarFase.setText("Adicionar");
        jBtAdicionarFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAdicionarFaseActionPerformed(evt);
            }
        });

        jBtRemoverFase.setText("Remover");
        jBtRemoverFase.setEnabled(false);

        jBtAddTarefa.setText("Adicionar tarefa");
        jBtAddTarefa.setEnabled(false);
        jBtAddTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAddTarefaActionPerformed(evt);
            }
        });

        jBtRemoveTarefa.setText("Remover tarefa");
        jBtRemoveTarefa.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSplitPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jBtAdicionarFase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtRemoverFase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(jBtAddTarefa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtRemoveTarefa)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtAdicionarFase)
                    .addComponent(jBtRemoverFase)
                    .addComponent(jBtAddTarefa)
                    .addComponent(jBtRemoveTarefa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jBtCancelar.setText("Sair");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtCancelar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jBtAdicionarFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAdicionarFaseActionPerformed
        if(!"".equals(jTxtDescricao.getText())){
            Fase f = new Fase(jTxtDescricao.getText(),this.Project_Id);
            try {
                DefaultListModel listmodel = (DefaultListModel) jLstFases.getModel();
                listmodel. addElement(f);

                f.setId(JmdiMain.facadeBL.put(f));

            } catch (PersistableException ex) {
                Logger.getLogger(JintFrmGerirFases.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        
    }//GEN-LAST:event_jBtAdicionarFaseActionPerformed

    private void jLstFasesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLstFasesValueChanged
        Fase f = (Fase)jLstFases.getSelectedValue();
        if(f!=null)  {
            this.jBtRemoverFase.setEnabled(true);
            this.jBtAddTarefa.setEnabled(true);
        }
        
        else this.jBtRemoverFase.setEnabled(false);
        this.LoadTarefas(f.getId());
        
        
    }//GEN-LAST:event_jLstFasesValueChanged

    private void jBtAddTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAddTarefaActionPerformed
        ImageIcon icon = new ImageIcon("");
       
        String s = (String)JOptionPane.showInputDialog(
        this    ,
        "Adicionar Tarefa",
        "Insira descrição da Tarefa:",
        JOptionPane.PLAIN_MESSAGE,
        icon,
        null,
        "");
        if(s!=null) {
            Fase faseSelecionada=(Fase)jLstFases.getSelectedValue();
            Tarefa tarefa = new Tarefa(s,faseSelecionada.getId(), null, null);

            try {
                JmdiMain.facadeBL.put(tarefa);
            } catch (PersistableException ex) {
                JOptionPane.showMessageDialog(this,"Ocorreu um erro ao gravar a Tarefa","Erro", JOptionPane.ERROR_MESSAGE);
            }
            this.LoadTarefas(faseSelecionada.getId());
        }
    }//GEN-LAST:event_jBtAddTarefaActionPerformed

    private void LoadTarefas(int Fase_Id) {
        try {
            List<Object> tarefas = JmdiMain.facadeBL.getAll(new Tarefa(), "Fase_Id", String.valueOf(Fase_Id));
            DefaultListModel listmodel = (DefaultListModel) jLstTarefas.getModel();
            listmodel.clear();
            for(Object obj : tarefas) {
                Tarefa t = (Tarefa)obj;
                listmodel. addElement(t);
            }
        } catch (PersistableException ex) {
            JOptionPane.showMessageDialog(this,"Ocorreu um erro ao carregar as Tarefas","Erro", JOptionPane.ERROR_MESSAGE);
        }       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAddTarefa;
    private javax.swing.JButton jBtAdicionarFase;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtRemoveTarefa;
    private javax.swing.JButton jBtRemoverFase;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JList jLstFases;
    private javax.swing.JList jLstTarefas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTxtDescricao;
    // End of variables declaration//GEN-END:variables
}
