/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIGeshabitat;

import BLGeshabitat.Fundos.Material;
import DAOGeshabitat.PersistableException;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class JintFrmSelectArtigo extends javax.swing.JInternalFrame{
    
    private final int modo; //  0 -> Doação | 1 -> Outro
    
    /**
     * Creates new form JintFrmNewArtigo
     * @param modo -- Tipo de modo, 0=doação, 1=outro, permite activar modo de edição de novos artigos
     */
    public JintFrmSelectArtigo(int modo) {

        this.modo = modo;
        initComponents();
        
        this.populateList();
        if(modo!=0) {
            jBtNew.setVisible(false);
            jBtRemover.setVisible(false);
        }
    }
    
    private void populateList() {
        try {
            List<Object> artigos = JmdiMain.facadeBL.getAll(new Material());
            DefaultTableModel tableModel = (DefaultTableModel)jTblArtigos.getModel();
            for(Object obj : artigos) {
                Material m = (Material) obj;
                tableModel.addRow(m.getRowData());
            }
        } catch (PersistableException ex) {
            JOptionPane.showMessageDialog(this,"Ocorreu um erro na obtencao da lista de Artigos!","Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jBtNew = new javax.swing.JButton();
        jBtCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblArtigos = new javax.swing.JTable();
        jBtRemover = new javax.swing.JButton();

        setClosable(true);
        setTitle("Artigos");

        jBtNew.setText("Novo");
        jBtNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNewActionPerformed(evt);
            }
        });

        jBtCancel.setText("Sair");
        jBtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelActionPerformed(evt);
            }
        });

        jTblArtigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descrição", "Stock"
            }
        ));
        jTblArtigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblArtigosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblArtigos);

        jBtRemover.setText("Remover");
        jBtRemover.setEnabled(false);
        jBtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jBtNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtCancel)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtCancel)
                    .addComponent(jBtNew)
                    .addComponent(jBtRemover))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNewActionPerformed
        ImageIcon icon = new ImageIcon("");
       
        String s = (String)JOptionPane.showInputDialog(
        this    ,
        "Insira descrição do novo artigo",
        "Novo artigo",
        JOptionPane.PLAIN_MESSAGE,
        icon,
        null,
        "");
        
        if(JmdiMain.exists(s,jTblArtigos,"Descrição")) {
            JOptionPane.showMessageDialog(this,"O artigo que inseriu já existe,\npor favor introduza um nome distinto.","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(s!=null) {
                
            Material m = new Material(s,0);
            int Id=-1;

            try {
                Id=JmdiMain.facadeBL.put(m);
                m.setId(Id);
            } catch (PersistableException ex) {
                JOptionPane.showMessageDialog(this,"Ocorreu um erro na criação do Artigo!","Erro", JOptionPane.ERROR_MESSAGE);
            }
            ((DefaultTableModel)this.jTblArtigos.getModel()).addRow(m.getRowData());
        }
    }//GEN-LAST:event_jBtNewActionPerformed


    private void jTblArtigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblArtigosMouseClicked
         int row = jTblArtigos.getSelectedRow();
        if(row!=-1) this.jBtRemover.setEnabled(true);
        else this.jBtRemover.setEnabled(false);
    }//GEN-LAST:event_jTblArtigosMouseClicked

    private void jBtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRemoverActionPerformed
        int row = jTblArtigos.getSelectedRow();  
        ((DefaultTableModel)this.jTblArtigos.getModel()).removeRow(row);
        //JmdiMain.reorderId(((DefaultTableModel)this.jTblArtigos.getModel()));
       //JmdiMain.facadeBL.delete(row, row);
    }//GEN-LAST:event_jBtRemoverActionPerformed

    private void jBtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtCancelActionPerformed

                                            


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCancel;
    private javax.swing.JButton jBtNew;
    private javax.swing.JButton jBtRemover;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblArtigos;
    // End of variables declaration//GEN-END:variables
}
