/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIGeshabitat;

import BLGeshabitat.Fundos.Doador;
import DAOGeshabitat.*;
import java.awt.Dimension;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class JintFrmNewDoador extends javax.swing.JInternalFrame {

    // components for Doador
    private javax.swing.JLabel label;
    private javax.swing.JRadioButton radio;
    private javax.swing.ButtonGroup group;
    

    public JintFrmNewDoador(String tipo) {
        initComponents();
        
        jLblActividade.setVisible(false);
        jTxtActividade.setVisible(false);
        
        if(tipo.equals("Funcionario")) { 
            jLblProfissao.setVisible(false); jTxtProfissao.setVisible(false);
        }
        
        if(tipo.equals("Doador")) { createCompDoador();
        }
        
    }
    
    private void createCompDoador() {
        jLblTipo.setVisible(true);
        jCmbTipo.setVisible(true);
        jChkParceria.setVisible(true);
        Dimension d = this.getSize();
        d.setSize(d.width, d.height+40);
        this.setSize(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtSair = new javax.swing.JButton();
        jBtAdd = new javax.swing.JButton();
        jPanelInfoCand = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtNif = new javax.swing.JTextField();
        jLblEstadoCivil = new javax.swing.JLabel();
        jCmbEstadoCivil = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTxtTelefone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtRua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtCp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtLocalidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jLblActividade = new javax.swing.JLabel();
        jTxtActividade = new javax.swing.JTextField();
        jLblTipo = new javax.swing.JLabel();
        jCmbTipo = new javax.swing.JComboBox();
        jChkParceria = new javax.swing.JCheckBox();
        jLblProfissao = new javax.swing.JLabel();
        jTxtProfissao = new javax.swing.JTextField();
        jLblDtNascimento = new javax.swing.JLabel();
        jDpDtNascimento = new org.jdesktop.swingx.JXDatePicker();

        setClosable(true);
        setResizable(true);
        setTitle("Adicionar novo Doador");
        setToolTipText("");

        jBtSair.setText("Sair");
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        jBtAdd.setText("Adicionar");
        jBtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAddActionPerformed(evt);
            }
        });

        jPanelInfoCand.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Dados pessoais do Doador"));

        jLabel1.setText("Nome Completo:");

        jLabel2.setText("Contribuinte:");

        jLblEstadoCivil.setText("Estado Civil:");

        jCmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado ", "Viuvo" }));

        jLabel7.setText("Telemóvel:");

        jLabel9.setText("Rua:");

        jLabel10.setText("Cod. Postal:");

        jLabel11.setText("Localidade:");

        jLabel13.setText("Email:");

        jLblActividade.setText("Actividade:");
        jLblActividade.setVisible(false);

        jTxtActividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtActividadeActionPerformed(evt);
            }
        });
        jTxtActividade.setVisible(false);

        jLblTipo.setText("Tipo:");
        jLblTipo.setVisible(false);

        jCmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Particular", "Empresa" }));
        jCmbTipo.setVisible(false);
        jCmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbTipoActionPerformed(evt);
            }
        });

        jChkParceria.setText("Parceria");
        jChkParceria.setVisible(false);

        jLblProfissao.setText("Profissao:");

        jLblDtNascimento.setText("Data Nascimento:");

        DateFormat dateFormat = DateFormat.getDateInstance(DateFormat.LONG, Locale.forLanguageTag("pt"));
        jDpDtNascimento.setFormats(dateFormat);

        jDpDtNascimento.setDate(new Date());

        javax.swing.GroupLayout jPanelInfoCandLayout = new javax.swing.GroupLayout(jPanelInfoCand);
        jPanelInfoCand.setLayout(jPanelInfoCandLayout);
        jPanelInfoCandLayout.setHorizontalGroup(
            jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtNif, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLblTipo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtRua))
                                .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                    .addComponent(jChkParceria)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLblActividade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtActividade, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtCp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblProfissao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                        .addComponent(jLblEstadoCivil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCmbEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblDtNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDpDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelInfoCandLayout.setVerticalGroup(
            jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoCandLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblTipo)
                        .addComponent(jCmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTxtNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblDtNascimento)
                        .addComponent(jDpDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblEstadoCivil)
                        .addComponent(jCmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLblProfissao))
                    .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTxtCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTxtLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(jPanelInfoCandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtActividade)
                    .addComponent(jLblActividade)
                    .addComponent(jChkParceria, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelInfoCand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanelInfoCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtSair)
                    .addComponent(jBtAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtActividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtActividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtActividadeActionPerformed

    private void jBtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAddActionPerformed
        int Nif=-1;
        
        try{
        Nif = Integer.valueOf(jTxtNif.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,"O número de contrinuinte que inseriu não é válido","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String Telefone = jTxtTelefone.getText();
        boolean Parceria = jChkParceria.isSelected();
        String Tipo = (String)jCmbTipo.getSelectedItem();
        String Rua = jTxtRua.getText();
        String Email = jTxtEmail.getText();
        String Localidade = jTxtLocalidade.getText();
        String Nome = jTxtNome.getText();
        String Cp = jTxtCp.getText();
        
        
        String EstadoCivil;
        String Profissao;
        java.sql.Date DtNascimento;
        String Actividade;
        if(Tipo.equals("Particular")) {
             DtNascimento = new java.sql.Date(jDpDtNascimento.getDate().getTime());
             Profissao = jTxtProfissao.getText();
             EstadoCivil = (String)jCmbEstadoCivil.getSelectedItem();
             Actividade = null;
        } else {
            Actividade = jTxtActividade.getText();
            DtNascimento = null;
            Profissao = null;
            EstadoCivil = null;
        }
   
        Doador doador = new Doador(Nif,Nome, Telefone,Email, Rua, Localidade, Cp, DtNascimento, EstadoCivil, Profissao, Actividade, Tipo, Parceria);
        

 
        try {
            JmdiMain.facadeBL.put(doador);
            
        } catch (PersistableException ex) {
            JOptionPane.showMessageDialog(this,"Ocorreu um erro a criação do registo","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this,"Registo adicionado com sucesso!","Sucesso", JOptionPane.INFORMATION_MESSAGE);

        this.dispose();
    }//GEN-LAST:event_jBtAddActionPerformed

    private void jCmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbTipoActionPerformed
        if(((String)jCmbTipo.getSelectedItem()).equals("Empresa") && !(jLblActividade.isVisible())) {
            jLblActividade.setVisible(true);
            jTxtActividade.setVisible(true);
            jLblEstadoCivil.setVisible(false);
            jCmbEstadoCivil.setVisible(false);
            jLblDtNascimento.setVisible(false);
            jDpDtNascimento.setVisible(false);
            jLblProfissao.setVisible(false);
            jTxtProfissao.setVisible(false);
            this.setSize(this.getSize().width, this.getSize().height-30);
        }
        else if (((String)jCmbTipo.getSelectedItem()).equals("Particular") && (jLblActividade.isVisible())){
            jLblActividade.setVisible(false);
            jTxtActividade.setVisible(false);
            jLblEstadoCivil.setVisible(true);
            jCmbEstadoCivil.setVisible(true);
            jLblDtNascimento.setVisible(true);
            jDpDtNascimento.setVisible(true);
            jLblProfissao.setVisible(true);
            jTxtProfissao.setVisible(true);
            this.setSize(this.getSize().width, this.getSize().height+30);     
        }
    }//GEN-LAST:event_jCmbTipoActionPerformed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAdd;
    private javax.swing.JButton jBtSair;
    private javax.swing.JCheckBox jChkParceria;
    private javax.swing.JComboBox jCmbEstadoCivil;
    private javax.swing.JComboBox jCmbTipo;
    private org.jdesktop.swingx.JXDatePicker jDpDtNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblActividade;
    private javax.swing.JLabel jLblDtNascimento;
    private javax.swing.JLabel jLblEstadoCivil;
    private javax.swing.JLabel jLblProfissao;
    private javax.swing.JLabel jLblTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelInfoCand;
    private javax.swing.JTextField jTxtActividade;
    private javax.swing.JTextField jTxtCp;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtLocalidade;
    private javax.swing.JTextField jTxtNif;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtProfissao;
    private javax.swing.JTextField jTxtRua;
    private javax.swing.JTextField jTxtTelefone;
    // End of variables declaration//GEN-END:variables
}
