/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIGeshabitat;

import BLGeshabitat.Projectos.Tarefa;
import DAOGeshabitat.PersistableException;
import UIGeshabitat.JmdiMain;
import UIGeshabitat.ModalJinternalFrame;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class JintFrmTarefas extends ModalJinternalFrame {
    
    private boolean tipo;  // true false iniciada | true concluida
    private int Project_Id;

    /**
     * Creates new form JintFrmTarefas
     * @param tipo
     */
    public JintFrmTarefas(boolean tipo, int Project_Id) {
        this.Project_Id=Project_Id;
        this.tipo = tipo;
        initComponents();
        if(tipo) {
            jLblTarefa.setText("Tarefas não iniciadas:");
            jLblDt.setText("Data de inicio:");
            try {
                this.getTarefasNIniciadas();
            } catch (PersistableException ex) {
                Logger.getLogger(JintFrmTarefas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            try {
                this.getTarefasIniciadas();
            } catch (PersistableException ex) {
                Logger.getLogger(JintFrmTarefas.class.getName()).log(Level.SEVERE, null, ex);
            }
            jLblTarefa.setText("Tarefa não concluidas:");
            jLblDt.setText("Data de conclusão:");
        }
    }
    
    public void getTarefasNIniciadas() throws PersistableException {
        jCmbTarefas.removeAllItems();
        for(Tarefa t : JmdiMain.facadeBL.getTarefasNIniciadas(Project_Id)) {
            jCmbTarefas.addItem(t);
        }
    }
    
    public void getTarefasIniciadas() throws PersistableException {
        jCmbTarefas.removeAllItems();
        for(Tarefa t : JmdiMain.facadeBL.getTarefasIniciadas(Project_Id)) {
            jCmbTarefas.addItem(t);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtOk = new javax.swing.JButton();
        jCmbTarefas = new javax.swing.JComboBox();
        jBtCancel = new javax.swing.JButton();
        jLblTarefa = new javax.swing.JLabel();
        jLblDt = new javax.swing.JLabel();
        jDpData = new org.jdesktop.swingx.JXDatePicker();

        setClosable(true);
        setTitle("Gestão de Tarefas");

        jBtOk.setText("Ok");
        jBtOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtOkActionPerformed(evt);
            }
        });

        jBtCancel.setText("Cancelar");
        jBtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelActionPerformed(evt);
            }
        });

        jLblTarefa.setText("Tarefa iniciada:");

        jLblDt.setText("Data inicio:");

        DateFormat dateFormat = DateFormat.getDateInstance(DateFormat.LONG, Locale.forLanguageTag("pt"));
        jDpData.setFormats(dateFormat);

        jDpData.setDate(new Date());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblDt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtOk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jBtCancel))
                            .addComponent(jDpData, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblTarefa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCmbTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTarefa))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDt)
                    .addComponent(jDpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtOk)
                    .addComponent(jBtCancel))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtOkActionPerformed
        Tarefa t = (Tarefa)jCmbTarefas.getSelectedItem();

        try {
            if (this.tipo)
                JmdiMain.facadeBL.update(new Tarefa(),"Data_inicio", this.jDpData.getDate(), t.getId());
            else
                JmdiMain.facadeBL.update(new Tarefa(),"Data_conclusao", this.jDpData.getDate(), t.getId());
            
            JOptionPane.showMessageDialog(this,"Data  registada com sucesso!","Sucesso", JOptionPane.INFORMATION_MESSAGE);

        } catch (PersistableException ex) {
            Logger.getLogger(JintFrmTarefas.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            
            this.dispose();
            
        }
    }//GEN-LAST:event_jBtOkActionPerformed

    private void jBtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCancel;
    private javax.swing.JButton jBtOk;
    private javax.swing.JComboBox jCmbTarefas;
    private org.jdesktop.swingx.JXDatePicker jDpData;
    private javax.swing.JLabel jLblDt;
    private javax.swing.JLabel jLblTarefa;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
