/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIGeshabitat;

import BLGeshabitat.Fundos.Doacao;
import BLGeshabitat.Fundos.Material;
import DAOGeshabitat.PersistableException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class JintFrmViewArtigos extends javax.swing.JInternalFrame{
    

    private int Doacao_Id;

    
    public JintFrmViewArtigos(int Doacao) {
        this.Doacao_Id=Doacao;
        initComponents();
        
        this.populateList();

    }
    
    private void populateList() {
        try {
            List<Material> materiais = JmdiMain.facadeBL.getDoacoesMateriais(Doacao_Id);
            
            DefaultTableModel tableModel = (DefaultTableModel)jTblArtigos.getModel();
            for(Object obj : materiais) {
                Material m = (Material) obj;
                tableModel.addRow(m.getRowData());
            }
        } catch (PersistableException ex) {
            Logger.getLogger(JintFrmViewArtigos.class.getName()).log(Level.SEVERE, null, ex);
        }
         

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jBtCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblArtigos = new javax.swing.JTable();

        setClosable(true);
        setTitle("Artigos");

        jPanelMain.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Artigos Doados"));

        jBtCancel.setText("Sair");
        jBtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelActionPerformed(evt);
            }
        });

        jTblArtigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descrição", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblArtigos.setColumnSelectionAllowed(true);
        jTblArtigos.getTableHeader().setReorderingAllowed(false);
        jTblArtigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblArtigosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblArtigos);
        jTblArtigos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtCancel)
                .addGap(25, 25, 25))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtCancel)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jTblArtigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblArtigosMouseClicked

    }//GEN-LAST:event_jTblArtigosMouseClicked

    private void jBtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtCancelActionPerformed

                                            


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCancel;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblArtigos;
    // End of variables declaration//GEN-END:variables
}
