/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIGeshabitat;

import BLGeshabitat.Fase;
import BLGeshabitat.Material;
import DAOGeshabitat.PersistableException;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nelson
 */
public class JintFrmAlocarMaterial extends ModalJinternalFrame {
    private int Project_Id;
    DateFormat dateFormat = DateFormat.getDateInstance(DateFormat.LONG, Locale.forLanguageTag("pt"));
    /**
     * Creates new form JintFrmAlocarMaterial
     */
    public JintFrmAlocarMaterial(int Project_Id) {
        this.Project_Id=Project_Id;
        initComponents();
        try {
            this.getFases();
            this.getArtigos();
        } catch (PersistableException ex) {
            JOptionPane.showMessageDialog(this,"Ocorreu um erro ao obter os artigos/fases","Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblMaterialAlocado = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jCmbArtigos = new javax.swing.JComboBox();
        jBtSelectArtigo = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jBtAdicionar = new javax.swing.JButton();
        jBtRemover = new javax.swing.JButton();
        jCmbFases = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jLblStock = new javax.swing.JLabel();
        jDpData = new org.jdesktop.swingx.JXDatePicker();
        jTxtQuantidade = new javax.swing.JTextField();
        jBtCancelar = new javax.swing.JButton();
        jBtGuardar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registo de Material");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Alocar Material"));

        jTblMaterialAlocado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Descrição", "Quantidade", "Fase"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblMaterialAlocado.setColumnSelectionAllowed(true);
        jTblMaterialAlocado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblMaterialAlocadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblMaterialAlocado);
        jTblMaterialAlocado.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel22.setText("Data:");

        jLabel23.setText("Descrição:");

        jCmbArtigos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Saco cimento" }));
        jCmbArtigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbArtigosActionPerformed(evt);
            }
        });

        jBtSelectArtigo.setText("...");
        jBtSelectArtigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSelectArtigoActionPerformed(evt);
            }
        });

        jLabel24.setText("Quantidade:");

        jBtAdicionar.setText("Adicionar");
        jBtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAdicionarActionPerformed(evt);
            }
        });

        jBtRemover.setText("Remover");
        jBtRemover.setEnabled(false);
        jBtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRemoverActionPerformed(evt);
            }
        });

        jCmbFases.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fase 1 - Demolições" }));

        jLabel25.setText("Fase:");

        jLblStock.setText("Stock");

        jDpData.setFormats(dateFormat);

        jDpData.setDate(new Date());

        jTxtQuantidade.setText("1.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBtAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtRemover))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbArtigos, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtSelectArtigo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLblStock))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(6, 6, 6)
                                .addComponent(jDpData, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbFases, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 185, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jCmbFases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jDpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbArtigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jBtSelectArtigo)
                    .addComponent(jLabel24)
                    .addComponent(jLblStock)
                    .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtAdicionar)
                    .addComponent(jBtRemover))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        jBtCancelar.setText("Cancelar");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });

        jBtGuardar.setText("Guardar");
        jBtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtCancelar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtCancelar)
                    .addComponent(jBtGuardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtSelectArtigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSelectArtigoActionPerformed
        JintFrmSelectArtigo frmArtigos = new JintFrmSelectArtigo(1);
        this.getDesktopPane().add(frmArtigos);
        frmArtigos.setVisible(true);
    }//GEN-LAST:event_jBtSelectArtigoActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jCmbArtigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbArtigosActionPerformed
        if(jCmbArtigos.getSelectedItem()!=null) {
            int Material_Id = ((Material)jCmbArtigos.getSelectedItem()).getId();
            String Stock = "";
            try {
                Stock = JmdiMain.facadeBL.getField(new Material(), "Stock" , "Id", Material_Id);
                this.jLblStock.setText("(Stock="+Stock+")");
            } catch (PersistableException ex) {
                JOptionPane.showMessageDialog(this,"Ocorreu um erro ao obter o stock","Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_jCmbArtigosActionPerformed

    private void jBtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAdicionarActionPerformed
        Material m = (Material)this.jCmbArtigos.getSelectedItem();
        Fase f = (Fase)this.jCmbFases.getSelectedItem();
        float Quantidade=0;
        String Stock="";
        try {
            Quantidade = Float.valueOf(jTxtQuantidade.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,"A quantidade que inseriu não é valida","Erro", JOptionPane.ERROR_MESSAGE);  
            return;
        }
        
        try {
            Stock = JmdiMain.facadeBL.getField(new Material(), "Stock" , "Id", m.getId());
        } catch (PersistableException ex) {
            JOptionPane.showMessageDialog(this,"Ocorreu um erro ao obter o stock","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(Quantidade > Float.valueOf(Stock) || Quantidade <= 0 ) {
            JOptionPane.showMessageDialog(this,"A quantidade que inseriu não é valida","Erro", JOptionPane.ERROR_MESSAGE); 
            return;
        }
        
        DefaultTableModel tablemodel = (DefaultTableModel)this.jTblMaterialAlocado.getModel();
        Object[] registo = {new java.sql.Date(this.jDpData.getDate().getTime()), m, Quantidade, f};
        tablemodel.addRow(registo);
        
    }//GEN-LAST:event_jBtAdicionarActionPerformed

    private void jTblMaterialAlocadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblMaterialAlocadoMouseClicked
        int row = jTblMaterialAlocado.getSelectedRow();
        if(row!=-1) this.jBtRemover.setEnabled(true);
        else this.jBtRemover.setEnabled(false);
    }//GEN-LAST:event_jTblMaterialAlocadoMouseClicked

    private void jBtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRemoverActionPerformed
        int row = jTblMaterialAlocado.getSelectedRow();  
        ((DefaultTableModel)this.jTblMaterialAlocado.getModel()).removeRow(row);
      // JmdiMain.reorderId(((DefaultTableModel)this.jTblAgregado.getModel()));
        this.jBtRemover.setEnabled(false);
    }//GEN-LAST:event_jBtRemoverActionPerformed

    private void jBtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGuardarActionPerformed
        List<Date> datas = new ArrayList<>();
        List<Material> materiais = new ArrayList<>();
        List<Float> quantidades = new ArrayList<>();
        List<Fase> fases = new ArrayList<>();
        
        for(int i=0; i< jTblMaterialAlocado.getRowCount(); i++) {
            datas.add((Date)jTblMaterialAlocado.getValueAt(i, 0));
            materiais.add((Material) jTblMaterialAlocado.getValueAt(i, 1));
            quantidades.add((Float) jTblMaterialAlocado.getValueAt(i, 2));
            fases.add((Fase) jTblMaterialAlocado.getValueAt(i, 3));
        }
        
        try {
          JmdiMain.facadeBL.alocaMateriais(datas,materiais,quantidades,fases);
        } catch (PersistableException ex) {
           JOptionPane.showMessageDialog(this,"Não foi possivel guardar registo!","Erro", JOptionPane.ERROR_MESSAGE); 
           return;
        }
        JOptionPane.showMessageDialog(this,"Registo adicionado com sucesso!","Sucesso", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_jBtGuardarActionPerformed

    private void getFases() throws PersistableException {
        List<Object> fases = JmdiMain.facadeBL.getAll(new Fase(),"Projecto_Id",String.valueOf(this.Project_Id));
        this.jCmbFases.removeAllItems();
        for(Object obj : fases) {
            Fase f = (Fase)obj;
            this.jCmbFases.addItem(f);
        }
        
    }
    
    private void getArtigos() throws PersistableException {
        List<Object> artigos = JmdiMain.facadeBL.getAll(new Material());
        this.jCmbArtigos.removeAllItems();
        for(Object obj : artigos) {
            Material m = (Material)obj;
            this.jCmbArtigos.addItem(m);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAdicionar;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtGuardar;
    private javax.swing.JButton jBtRemover;
    private javax.swing.JButton jBtSelectArtigo;
    private javax.swing.JComboBox jCmbArtigos;
    private javax.swing.JComboBox jCmbFases;
    private org.jdesktop.swingx.JXDatePicker jDpData;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLblStock;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblMaterialAlocado;
    private javax.swing.JTextField jTxtQuantidade;
    // End of variables declaration//GEN-END:variables
}
