/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIGeshabitat;

import BLGeshabitat.Candidatura;
import BLGeshabitat.FacadeBL;
import DAOGeshabitat.DBConnection;
import static DAOGeshabitat.FacadeDAO.conn;
import DAOGeshabitat.PersistableException;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Insets;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultDesktopManager;
import javax.swing.DesktopManager;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JComponent;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import javax.swing.event.MenuEvent;
import javax.swing.event.MenuListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nelson
 */
public class JmdiMain extends javax.swing.JFrame implements InternalFrameListener{
    
    public static FacadeBL facadeBL;
    public static String configFile = "./connection.config";
    
    public static void reorderId(DefaultTableModel tableModel) {
        for(int i=0; i < tableModel.getRowCount(); i++) {
            tableModel.setValueAt(i+1, i, 0);
        }
    }
    
    public static boolean exists(String nome,JTable table,String coluna) {
        boolean ret=false;
        int column = 0;
        for(int i=0; i< table.getColumnCount(); i++) {
            if(table.getColumnName(i).equals(coluna)) column=i;
        }

        for(int i=0;i<table.getRowCount();i++) {
            if(nome.equals(table.getValueAt(i, column))) return true;
        }
        return false;
    }
    
     
    /**
     * Creates new form jMdiMain
     */
    public JmdiMain() {
        DBConnection connection = null;
        try {
             connection = DBConnection.load(configFile);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Não foi possivel carregar as configurações da Base Dados.\nPor favor efectue novas configuraçoes através da opção Setup Connection accessivel no menu File","Erro", JOptionPane.ERROR_MESSAGE);
        } 
        
        
        if(connection!=null) try {
            facadeBL = new FacadeBL(connection);
        } catch (PersistableException ex) {
            JOptionPane.showMessageDialog(this,"Não foi possivel estabelecer conexão à Base Dados.\nVerifique as definições e volte a tentar","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        initComponents();


        jScrollDesktopMain.getVerticalScrollBar().setUnitIncrement(16);
        jPanelProject.setVisible(false);
        jPanelSearch.setVisible(false);
        jPanelDefault.setVisible(true);
        jPanelCandidatura.setVisible(false);
        this.setExtendedState(Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jMainToolBar = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jbtProcurar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jBtNewCand = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jBtFuncionario = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jBtVoluntario = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jBtDoador = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jBtDoacao = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jBtDonativos = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jBtUserMan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jStatusBar = new javax.swing.JPanel();
        jLeftPanelLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollDesktopMain = new javax.swing.JScrollPane();
        jDesktopPaneMain = new MDIDesktopPane();
        jLayeredPaneLeft = new javax.swing.JLayeredPane();
        jPanelDefault = new SidePanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        jPanelCandidatura = new SidePanel();
        jPanel7 = new javax.swing.JPanel();
        jBtAprovarCand = new javax.swing.JButton();
        jPanelProject = new SidePanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jBtConcluirTarefa = new javax.swing.JButton();
        jBtInitTarefa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jBtPlaneamento = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jBtRegistoMaterial = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        jBtVoluntariado = new javax.swing.JButton();
        jPanelSearch = new SidePanel();
        jButton11 = new javax.swing.JButton();
        jBarraMenus = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMnuConnectionSetup = new javax.swing.JMenuItem();
        jMenuWindow = new WindowMenu((MDIDesktopPane)jDesktopPaneMain);
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geshabitat");
        setExtendedState(6);

        jMainToolBar.setFloatable(false);
        jMainToolBar.setToolTipText("");
        jMainToolBar.setFocusable(false);

        jSeparator1.setSeparatorSize(new java.awt.Dimension(20, 10));
        jMainToolBar.add(jSeparator1);

        jbtProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIGeshabitat/icons/search_small.png"))); // NOI18N
        jbtProcurar.setToolTipText("Procurar");
        jbtProcurar.setFocusable(false);
        jbtProcurar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtProcurar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtProcurarActionPerformed(evt);
            }
        });
        jMainToolBar.add(jbtProcurar);
        jMainToolBar.add(jSeparator4);

        jBtNewCand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIGeshabitat/icons/candidatura.png"))); // NOI18N
        jBtNewCand.setToolTipText("Nova Candidatura");
        jBtNewCand.setFocusable(false);
        jBtNewCand.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtNewCand.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtNewCand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNewCandActionPerformed(evt);
            }
        });
        jMainToolBar.add(jBtNewCand);
        jMainToolBar.add(jSeparator5);

        jBtFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIGeshabitat/icons/funcionario.png"))); // NOI18N
        jBtFuncionario.setToolTipText("Novo Funcionário");
        jBtFuncionario.setFocusable(false);
        jBtFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtFuncionario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFuncionarioActionPerformed(evt);
            }
        });
        jMainToolBar.add(jBtFuncionario);
        jMainToolBar.add(jSeparator6);

        jBtVoluntario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIGeshabitat/icons/funcionarios.png"))); // NOI18N
        jBtVoluntario.setToolTipText("Novo Voluntário");
        jBtVoluntario.setFocusable(false);
        jBtVoluntario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtVoluntario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtVoluntarioActionPerformed(evt);
            }
        });
        jMainToolBar.add(jBtVoluntario);
        jMainToolBar.add(jSeparator7);

        jBtDoador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIGeshabitat/icons/doador_small.png"))); // NOI18N
        jBtDoador.setToolTipText("Novo Doador");
        jBtDoador.setFocusable(false);
        jBtDoador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtDoador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDoadorActionPerformed(evt);
            }
        });
        jMainToolBar.add(jBtDoador);
        jMainToolBar.add(jSeparator8);

        jBtDoacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIGeshabitat/icons/donation-icon.png"))); // NOI18N
        jBtDoacao.setToolTipText("Nova Doação");
        jBtDoacao.setFocusable(false);
        jBtDoacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtDoacao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDoacaoActionPerformed(evt);
            }
        });
        jMainToolBar.add(jBtDoacao);
        jMainToolBar.add(jSeparator9);

        jBtDonativos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIGeshabitat/icons/managment.png"))); // NOI18N
        jBtDonativos.setToolTipText("Gestão de Donativos");
        jBtDonativos.setFocusable(false);
        jBtDonativos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtDonativos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtDonativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDonativosActionPerformed(evt);
            }
        });
        jMainToolBar.add(jBtDonativos);
        jMainToolBar.add(jSeparator3);
        jMainToolBar.add(jSeparator12);
        jMainToolBar.add(jSeparator11);
        jMainToolBar.add(jSeparator10);

        jBtUserMan.setText("Users");
        jBtUserMan.setFocusable(false);
        jBtUserMan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtUserMan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtUserMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtUserManActionPerformed(evt);
            }
        });
        jMainToolBar.add(jBtUserMan);

        jButton2.setText("Novo Login");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jMainToolBar.add(jButton2);
        jMainToolBar.add(jSeparator13);

        jStatusBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jStatusBarLayout = new javax.swing.GroupLayout(jStatusBar);
        jStatusBar.setLayout(jStatusBarLayout);
        jStatusBarLayout.setHorizontalGroup(
            jStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jStatusBarLayout.setVerticalGroup(
            jStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIGeshabitat/pictures/logotipo_habitat_trans.png"))); // NOI18N

        javax.swing.GroupLayout jLeftPanelLogoLayout = new javax.swing.GroupLayout(jLeftPanelLogo);
        jLeftPanelLogo.setLayout(jLeftPanelLogoLayout);
        jLeftPanelLogoLayout.setHorizontalGroup(
            jLeftPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jLeftPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLeftPanelLogoLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLeftPanelLogoLayout.setVerticalGroup(
            jLeftPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
            .addGroup(jLeftPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLeftPanelLogoLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jScrollDesktopMain.setViewportView(jDesktopPaneMain);

        jLayeredPaneLeft.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPaneLeft.setLayout(new javax.swing.OverlayLayout(jLayeredPaneLeft));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Bloco Notas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        dateChooserPanel1.setCurrentView(new datechooser.view.appearance.AppearancesList("Dali",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.BOLD, 12),
                    new java.awt.Color(51, 51, 51),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.BOLD, 12),
                    new java.awt.Color(51, 51, 51),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.BOLD, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.BOLD, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.BOLD, 12),
                    new java.awt.Color(51, 51, 51),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.BOLD, 12),
                    new java.awt.Color(51, 51, 51),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.LOWERED,
        (java.awt.Color)null,
        (java.awt.Color)null));
dateChooserPanel1.setLocale(new java.util.Locale("pt", "", ""));
dateChooserPanel1.setLocked(true);
dateChooserPanel1.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
jPanel1.setLayout(jPanel1Layout);
jPanel1Layout.setHorizontalGroup(
    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addComponent(dateChooserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(dateChooserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanelDefaultLayout = new javax.swing.GroupLayout(jPanelDefault);
    jPanelDefault.setLayout(jPanelDefaultLayout);
    jPanelDefaultLayout.setHorizontalGroup(
        jPanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelDefaultLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanelDefaultLayout.setVerticalGroup(
        jPanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelDefaultLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    jLayeredPaneLeft.add(jPanelDefault);

    jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Candidatura", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

    jBtAprovarCand.setText("Aprovar Candidatura");
    jBtAprovarCand.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBtAprovarCandActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jBtAprovarCand, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jBtAprovarCand)
            .addContainerGap(528, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanelCandidaturaLayout = new javax.swing.GroupLayout(jPanelCandidatura);
    jPanelCandidatura.setLayout(jPanelCandidaturaLayout);
    jPanelCandidaturaLayout.setHorizontalGroup(
        jPanelCandidaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelCandidaturaLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanelCandidaturaLayout.setVerticalGroup(
        jPanelCandidaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelCandidaturaLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    jLayeredPaneLeft.add(jPanelCandidatura);

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Projecto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Tarefas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

    jBtConcluirTarefa.setText("Concluir Tarefa");
    jBtConcluirTarefa.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBtConcluirTarefaActionPerformed(evt);
        }
    });

    jBtInitTarefa.setText("Iniciar Tarefa");
    jBtInitTarefa.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBtInitTarefaActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jBtInitTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtConcluirTarefa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jBtInitTarefa)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jBtConcluirTarefa)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Gerir Fases/Tarefas"));

    jBtPlaneamento.setText("Definir Planeamento");
    jBtPlaneamento.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBtPlaneamentoActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jBtPlaneamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jBtPlaneamento)
            .addContainerGap())
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Registo Material Usado"));

    jBtRegistoMaterial.setText("Registo Material");
    jBtRegistoMaterial.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBtRegistoMaterialActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jBtRegistoMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jBtRegistoMaterial)
            .addContainerGap())
    );

    jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Estado Projecto"));

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Em execução" }));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Registo Voluntariado"));

    jBtVoluntariado.setText("Registo Voluntariado");
    jBtVoluntariado.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBtVoluntariadoActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jBtVoluntariado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel8Layout.setVerticalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jBtVoluntariado)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanelProjectLayout = new javax.swing.GroupLayout(jPanelProject);
    jPanelProject.setLayout(jPanelProjectLayout);
    jPanelProjectLayout.setHorizontalGroup(
        jPanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelProjectLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanelProjectLayout.setVerticalGroup(
        jPanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelProjectLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    jLayeredPaneLeft.add(jPanelProject);

    jButton11.setText("jButton11");

    javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
    jPanelSearch.setLayout(jPanelSearchLayout);
    jPanelSearchLayout.setHorizontalGroup(
        jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelSearchLayout.createSequentialGroup()
            .addGap(50, 50, 50)
            .addComponent(jButton11)
            .addContainerGap(128, Short.MAX_VALUE))
    );
    jPanelSearchLayout.setVerticalGroup(
        jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelSearchLayout.createSequentialGroup()
            .addGap(68, 68, 68)
            .addComponent(jButton11)
            .addContainerGap(533, Short.MAX_VALUE))
    );

    jLayeredPaneLeft.add(jPanelSearch);

    jMenuFile.setText("Ficheiro");

    jMnuConnectionSetup.setText("Configurar Conexão");
    jMnuConnectionSetup.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMnuConnectionSetupActionPerformed(evt);
        }
    });
    jMenuFile.add(jMnuConnectionSetup);

    jBarraMenus.add(jMenuFile);

    jMenuWindow.setText("Janela");
    jBarraMenus.add(jMenuWindow);

    jMenu1.setText("Ajuda");
    jBarraMenus.add(jMenu1);

    setJMenuBar(jBarraMenus);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jStatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLeftPanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPaneLeft))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollDesktopMain, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
            .addContainerGap())
        .addComponent(jMainToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jMainToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLeftPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLayeredPaneLeft))
                .addComponent(jScrollDesktopMain))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jBtPlaneamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPlaneamentoActionPerformed
        int Project_Id = ((JintFrmProject)((SidePanel)this.jPanelProject).getjIntFrame()).Project_Id;
        
        JintFrmGerirFases frmFases = new JintFrmGerirFases(Project_Id);
        frmFases.addInternalFrameListener(this);
        this.jDesktopPaneMain.add(frmFases);
        frmFases.setVisible(true);
        frmFases.setLayer(20);
        
    }//GEN-LAST:event_jBtPlaneamentoActionPerformed

    private void jBtRegistoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRegistoMaterialActionPerformed
        int Project_Id = ((JintFrmProject)((SidePanel)this.jPanelProject).getjIntFrame()).Project_Id;
        JintFrmAlocarMaterial frmMaterial = new JintFrmAlocarMaterial(Project_Id);
        frmMaterial.addInternalFrameListener(this);
        this.jDesktopPaneMain.add(frmMaterial);
        frmMaterial.setVisible(true);
        frmMaterial.setLayer(20);
        
    }//GEN-LAST:event_jBtRegistoMaterialActionPerformed

    private void jBtInitTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtInitTarefaActionPerformed
        int Project_Id = ((JintFrmProject)((SidePanel)this.jPanelProject).getjIntFrame()).Project_Id;        
        JintFrmTarefas frmTarefas = new JintFrmTarefas(true,Project_Id);
        frmTarefas.addInternalFrameListener(this);
        this.jDesktopPaneMain.add(frmTarefas);
        frmTarefas.setVisible(true);
        frmTarefas.setLayer(21);        
    }//GEN-LAST:event_jBtInitTarefaActionPerformed

    private void jBtConcluirTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConcluirTarefaActionPerformed
        int Project_Id = ((JintFrmProject)((SidePanel)this.jPanelProject).getjIntFrame()).Project_Id;
        JintFrmTarefas frmTarefas = new JintFrmTarefas(false,Project_Id);
        frmTarefas.addInternalFrameListener(this);
        this.jDesktopPaneMain.add(frmTarefas);
        frmTarefas.setVisible(true);  
        frmTarefas.setLayer(22);
    }//GEN-LAST:event_jBtConcluirTarefaActionPerformed

    private void jMnuConnectionSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConnectionSetupActionPerformed
        JintFrmDBConnection frmDBConnection = new JintFrmDBConnection();
        //frmTarefas.addInternalFrameListener(this);
        this.jDesktopPaneMain.add(frmDBConnection);
        frmDBConnection.setVisible(true); 
        
    }//GEN-LAST:event_jMnuConnectionSetupActionPerformed

    private void jBtAprovarCandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAprovarCandActionPerformed
        int dialogButton = 0;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Tem a certeza que deseja continuar?\nEsta alteração não pode ser desfeita e dará inicio a um novo projecto","Aviso",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION) {
        
            Candidatura c = ((JintFrmNewCand)((SidePanel)jPanelCandidatura).getjIntFrame()).getCand();
            JintFrmNewProject frmNewProject = new JintFrmNewProject(c.getId(),c.getFuncionario_Id());
            frmNewProject.addInternalFrameListener(this);
            this.jDesktopPaneMain.add(frmNewProject);
            frmNewProject.setVisible(true);  
        }
    }//GEN-LAST:event_jBtAprovarCandActionPerformed

    private void jBtVoluntariadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtVoluntariadoActionPerformed
        int Project_Id = ((JintFrmProject)((SidePanel)this.jPanelProject).getjIntFrame()).Project_Id;
        JintFrmAlocarVoluntarios frmVoluntarios = new JintFrmAlocarVoluntarios(Project_Id);
        frmVoluntarios.addInternalFrameListener(this);
        this.jDesktopPaneMain.add(frmVoluntarios);
        frmVoluntarios.setVisible(true);
        frmVoluntarios.setLayer(20);
    }//GEN-LAST:event_jBtVoluntariadoActionPerformed

    private void jBtDonativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDonativosActionPerformed
        JintFrmDonations jfrmDoacoes = new JintFrmDonations(jPanelDefault);

        jDesktopPaneMain.add(jfrmDoacoes);

        jfrmDoacoes.addInternalFrameListener(this);

        ((MDIDesktopPane)jDesktopPaneMain).checkDesktopSize();
        jfrmDoacoes.setVisible(true);

    }//GEN-LAST:event_jBtDonativosActionPerformed

    private void jBtDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDoacaoActionPerformed
        JintFrmNewDonation jfrmNewDoacao = new JintFrmNewDonation();
        jfrmNewDoacao.addInternalFrameListener(this); 
        jDesktopPaneMain.add(jfrmNewDoacao);
        ((MDIDesktopPane)jDesktopPaneMain).checkDesktopSize();
        jfrmNewDoacao.setVisible(true);
    }//GEN-LAST:event_jBtDoacaoActionPerformed

    private void jBtDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDoadorActionPerformed
        JintFrmNewDoador jfrmNewDoador = new JintFrmNewDoador("Doador");
        jfrmNewDoador.addInternalFrameListener(this);    
        jDesktopPaneMain.add(jfrmNewDoador);
        ((MDIDesktopPane)jDesktopPaneMain).checkDesktopSize();
        jfrmNewDoador.setVisible(true);
    }//GEN-LAST:event_jBtDoadorActionPerformed

    private void jBtVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtVoluntarioActionPerformed
        JintFrmNewVoluntario jfrmNewVoluntario = new JintFrmNewVoluntario();
        jfrmNewVoluntario.addInternalFrameListener(this);
        jDesktopPaneMain.add(jfrmNewVoluntario);
        ((MDIDesktopPane)jDesktopPaneMain).checkDesktopSize();
        jfrmNewVoluntario.setVisible(true);
    }//GEN-LAST:event_jBtVoluntarioActionPerformed

    private void jBtFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFuncionarioActionPerformed
        JintFrmNewFuncionario jfrmNewFuncionario = new JintFrmNewFuncionario();
         jfrmNewFuncionario.addInternalFrameListener(this);       
        jDesktopPaneMain.add(jfrmNewFuncionario);
        ((MDIDesktopPane)jDesktopPaneMain).checkDesktopSize();
        jfrmNewFuncionario.setVisible(true);
    }//GEN-LAST:event_jBtFuncionarioActionPerformed

    private void jBtNewCandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNewCandActionPerformed
        JintFrmNewCand jfrmNewCand = new JintFrmNewCand();
        jfrmNewCand.addInternalFrameListener(this);
        jDesktopPaneMain.add(jfrmNewCand);

        //        try {
            //            jfrmNewCand.setMaximum(true);
            //        } catch (PropertyVetoException ex) {
            //        }

        ((MDIDesktopPane)jDesktopPaneMain).checkDesktopSize();
        jfrmNewCand.setVisible(true);

    }//GEN-LAST:event_jBtNewCandActionPerformed

    private void jBtUserManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtUserManActionPerformed
        JintFrmUserManagment jfrmUsers = new JintFrmUserManagment();

        //position on center
        Dimension desktopSize = jDesktopPaneMain.getSize();
        Dimension frmLoginSize = jfrmUsers.getSize();
        jDesktopPaneMain.add(jfrmUsers);

        jfrmUsers.setLocation((desktopSize.width - frmLoginSize.width)/2,
            (desktopSize.height - frmLoginSize.height)/2);
        ((MDIDesktopPane)jDesktopPaneMain).checkDesktopSize();
        jfrmUsers.setVisible(true);
    }//GEN-LAST:event_jBtUserManActionPerformed

    private void jbtProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtProcurarActionPerformed
        JintFrmSearch jfrmMain = new JintFrmSearch();
        jfrmMain.addInternalFrameListener(this);
        jDesktopPaneMain.add(jfrmMain);

        try {
            jfrmMain.setMaximum(true);
        } catch (PropertyVetoException ex) {
        }
        ((MDIDesktopPane)jDesktopPaneMain).checkDesktopSize();
        jfrmMain.setVisible(true);
    }//GEN-LAST:event_jbtProcurarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JintFrmLogin jfrmLogin = new JintFrmLogin();
        Dimension desktopSize = jDesktopPaneMain.getSize();
        Dimension frmLoginSize = jfrmLogin.getSize();

        jfrmLogin.setLocation((desktopSize.width - frmLoginSize.width)/2,
            (desktopSize.height - frmLoginSize.height)/2);

        jfrmLogin.setVisible(true);

        jDesktopPaneMain.add(jfrmLogin);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JmdiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JmdiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JmdiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JmdiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JmdiMain().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private javax.swing.JMenuBar jBarraMenus;
    private javax.swing.JButton jBtAprovarCand;
    private javax.swing.JButton jBtConcluirTarefa;
    private javax.swing.JButton jBtDoacao;
    private javax.swing.JButton jBtDoador;
    private javax.swing.JButton jBtDonativos;
    private javax.swing.JButton jBtFuncionario;
    private javax.swing.JButton jBtInitTarefa;
    private javax.swing.JButton jBtNewCand;
    private javax.swing.JButton jBtPlaneamento;
    private javax.swing.JButton jBtRegistoMaterial;
    private javax.swing.JButton jBtUserMan;
    private javax.swing.JButton jBtVoluntariado;
    private javax.swing.JButton jBtVoluntario;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    public javax.swing.JDesktopPane jDesktopPaneMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPaneLeft;
    private javax.swing.JPanel jLeftPanelLogo;
    private javax.swing.JToolBar jMainToolBar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuWindow;
    private javax.swing.JMenuItem jMnuConnectionSetup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelCandidatura;
    private javax.swing.JPanel jPanelDefault;
    public javax.swing.JPanel jPanelProject;
    public javax.swing.JPanel jPanelSearch;
    private javax.swing.JScrollPane jScrollDesktopMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JPanel jStatusBar;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbtProcurar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent e) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent e) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent e) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent e) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent e) {
         if(e.getInternalFrame() instanceof JintFrmProject) {
            ((SidePanel)jPanelProject).setInternalFrame(e.getInternalFrame());
            jPanelProject.setVisible(true);
            jPanelDefault.setVisible(false);
            jPanelSearch.setVisible(false);
            jPanelCandidatura.setVisible(false);
        } else if (e.getInternalFrame() instanceof JintFrmNewCand){
            ((SidePanel)jPanelCandidatura).setInternalFrame(e.getInternalFrame());
            jPanelProject.setVisible(false);
            jPanelDefault.setVisible(false);
            jPanelSearch.setVisible(false);
            jPanelCandidatura.setVisible(true);
        } else if (e.getInternalFrame() instanceof JintFrmSearch){
            ((SidePanel)jPanelSearch).setInternalFrame(e.getInternalFrame());
            jPanelProject.setVisible(false);
            jPanelDefault.setVisible(false);
            jPanelSearch.setVisible(true);
            jPanelCandidatura.setVisible(false); 
        } else {
            jPanelProject.setVisible(false);
            jPanelSearch.setVisible(false);
            jPanelDefault.setVisible(true);
            jPanelCandidatura.setVisible(false);
        } 

    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent e) {
//        if(e.getInternalFrame() instanceof JintFrmProject)
//            ((JintFrmProject)e.getSource()).setLayer(8);
        
        if(e.getInternalFrame() instanceof ModalJinternalFrame)
            ((ModalJinternalFrame)e.getSource()).setLayer(8);

    }
}



/**
 * An extension of WDesktopPane that supports often used MDI functionality. This
 * class also handles setting scroll bars for when windows move too far to the
 * left or bottom, providing the MDIDesktopPane is in a ScrollPane.
 */
class MDIDesktopPane extends JDesktopPane {
  private static final int FRAME_OFFSET = 20;

  private final MDIDesktopManager manager;

  public MDIDesktopPane() {
    manager = new MDIDesktopManager(this);
    setDesktopManager((DesktopManager) manager);
    setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
  }

  @Override
  public void setBounds(int x, int y, int w, int h) {
    super.setBounds(x, y, w, h);
    checkDesktopSize();
  }

  public Component add(JInternalFrame frame) {
    JInternalFrame[] array = getAllFrames();
    Point p;
    int w;
    int h;

    Component retval = super.add(frame);
    checkDesktopSize();
    if (array.length > 0) {
      p = array[0].getLocation();
      p.x = p.x + FRAME_OFFSET;
      p.y = p.y + FRAME_OFFSET;
    } else {
      p = new Point(0, 0);
    }
    frame.setLocation(p.x, p.y);
    if (frame.isResizable()) {
      w = getWidth() - (getWidth() / 3);
      h = getHeight() - (getHeight() / 3);
      if (w < frame.getMinimumSize().getWidth())
        w = (int) frame.getMinimumSize().getWidth();
      if (h < frame.getMinimumSize().getHeight())
        h = (int) frame.getMinimumSize().getHeight();
      frame.setSize(w, h);
    }
    moveToFront(frame);
    frame.setVisible(true);
    try {
      frame.setSelected(true);
    } catch (PropertyVetoException e) {
      frame.toBack();
    }
    return retval;
  }

  @Override
  public void remove(Component c) {
    super.remove(c);
    checkDesktopSize();
  }

  /**
   * Cascade all internal frames
   */
  public void cascadeFrames() {
    int x = 0;
    int y = 0;
    JInternalFrame allFrames[] = getAllFrames();

    manager.setNormalSize();
    int frameHeight = (getBounds().height - 5) - allFrames.length * FRAME_OFFSET;
    int frameWidth = (getBounds().width - 5) - allFrames.length * FRAME_OFFSET;
    for (int i = allFrames.length - 1; i >= 0; i--) {
     // allFrames[i].setSize(frameWidth, frameHeight);
      allFrames[i].setLocation(x, y);
      x = x + FRAME_OFFSET;
      y = y + FRAME_OFFSET;
    }
    this.checkDesktopSize();
    
  }

  /**
   * Tile all internal frames
   */
  public void tileFrames() {
    java.awt.Component allFrames[] = getAllFrames();
    manager.setNormalSize();
    int frameHeight = getBounds().height / allFrames.length;
    int y = 0;
      for (Component allFrame : allFrames) {
        //  allFrame.setSize(getBounds().width, frameHeight);
          allFrame.setLocation(0, y);
          y = y + frameHeight;
      }
    this.checkDesktopSize();
  }

  /**
   * Sets all component size properties ( maximum, minimum, preferred) to the
   * given dimension.
   */
  public void setAllSize(Dimension d) {
    setMinimumSize(d);
    setMaximumSize(d);
    setPreferredSize(d);
  }

  /**
   * Sets all component size properties ( maximum, minimum, preferred) to the
   * given width and height.
   */
  public void setAllSize(int width, int height) {
    setAllSize(new Dimension(width, height));
  }

  public void checkDesktopSize() {
    if (getParent() != null && isVisible())
      manager.resizeDesktop();
  }
}



/**
 * Private class used to replace the standard DesktopManager for JDesktopPane.
 * Used to provide scrollbar functionality.
 */
class MDIDesktopManager extends DefaultDesktopManager {
  private final MDIDesktopPane desktop;

  public MDIDesktopManager(MDIDesktopPane desktop) {
    this.desktop = desktop;
  }

  @Override
  public void endResizingFrame(JComponent f) {
    super.endResizingFrame(f);
    resizeDesktop();
  }

  @Override
  public void endDraggingFrame(JComponent f) {
    super.endDraggingFrame(f);
    resizeDesktop();
  }

  public void setNormalSize() {
    JScrollPane scrollPane = getScrollPane();
    int x = 0;
    int y = 0;
    Insets scrollInsets = getScrollPaneInsets();

    if (scrollPane != null) {
      Dimension d = scrollPane.getVisibleRect().getSize();
      if (scrollPane.getBorder() != null) {
        d.setSize(d.getWidth() - scrollInsets.left - scrollInsets.right, d.getHeight()
            - scrollInsets.top - scrollInsets.bottom);
      }

      d.setSize(d.getWidth() - 20, d.getHeight() - 20);
      desktop.setAllSize(x, y);
      scrollPane.invalidate();
      scrollPane.validate();
    }
  }

  private Insets getScrollPaneInsets() {
    JScrollPane scrollPane = getScrollPane();
    if (scrollPane == null)
      return new Insets(0, 0, 0, 0);
    else
      return getScrollPane().getBorder().getBorderInsets(scrollPane);
  }

  private JScrollPane getScrollPane() {
    if (desktop.getParent() instanceof JViewport) {
      JViewport viewPort = (JViewport) desktop.getParent();
      if (viewPort.getParent() instanceof JScrollPane)
        return (JScrollPane) viewPort.getParent();
    }
    return null;
  }

  protected void resizeDesktop() {
    int x = 0;
    int y = 0;
    JScrollPane scrollPane = getScrollPane();
    Insets scrollInsets = getScrollPaneInsets();

    if (scrollPane != null) {
      JInternalFrame allFrames[] = desktop.getAllFrames();
      for (int i = 0; i < allFrames.length; i++) {
        if (allFrames[i].getX() + allFrames[i].getWidth() > x) {
          x = allFrames[i].getX() + allFrames[i].getWidth();
        }
        if (allFrames[i].getY() + allFrames[i].getHeight() > y) {
          y = allFrames[i].getY() + allFrames[i].getHeight();
        }
      }
      Dimension d = scrollPane.getVisibleRect().getSize();
      if (scrollPane.getBorder() != null) {
        d.setSize(d.getWidth() - scrollInsets.left - scrollInsets.right, d.getHeight()
            - scrollInsets.top - scrollInsets.bottom);
      }

      if (x <= d.getWidth())
        x = ((int) d.getWidth()) - 20;
      if (y <= d.getHeight())
        y = ((int) d.getHeight()) - 20;
      desktop.setAllSize(x, y);
      scrollPane.invalidate();
      scrollPane.validate();
    }
  }
}

/**
 * Menu component that handles the functionality expected of a standard
 * "Windows" menu for MDI applications.
 */
class WindowMenu extends JMenu {
  private MDIDesktopPane desktop;

  private final JMenuItem cascade = new JMenuItem("Cascata");
  private final JMenuItem tile = new JMenuItem("Mosaico");

  public WindowMenu(MDIDesktopPane desktop) {
    this.desktop = desktop;
    setText("Window");
    
    cascade.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent ae) {
        WindowMenu.this.desktop.cascadeFrames();
      }
    });
    
    tile.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent ae) {
        WindowMenu.this.desktop.tileFrames();
      }
    });
    
    addMenuListener(new MenuListener() {
      @Override
      public void menuCanceled(MenuEvent e) {
      }

      @Override
      public void menuDeselected(MenuEvent e) {
        removeAll();
      }

      @Override
      public void menuSelected(MenuEvent e) {
        buildChildMenus();
      }
    });
  }

  /* Sets up the children menus depending on the current desktop state */
  private void buildChildMenus() {
    int i;
    ChildMenuItem menu;
    JInternalFrame[] array = desktop.getAllFrames();

    add(cascade);
    add(tile);
    if (array.length > 0)
      addSeparator();
    cascade.setEnabled(array.length > 0);
    tile.setEnabled(array.length > 0);

    for (i = 0; i < array.length; i++) {
      menu = new ChildMenuItem(array[i],i+1);
      menu.setState(i == 0);
      menu.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
          JInternalFrame frame = ((ChildMenuItem) ae.getSource()).getFrame();
          frame.moveToFront();
          try {
            frame.setSelected(true);
          } catch (PropertyVetoException e) {
          }
        }
      });
      menu.setIcon(array[i].getFrameIcon());
      add(menu);
    }
  }

  /*
   * This JCheckBoxMenuItem descendant is used to track the child frame that
   * corresponds to a give menu.
   */
  class ChildMenuItem extends JCheckBoxMenuItem {
    private final JInternalFrame frame;
    
    public ChildMenuItem(JInternalFrame frame, int pos) {
      super(String.valueOf(pos) +" - "+frame.getTitle());
      this.frame = frame;
    }

    public JInternalFrame getFrame() {
      return frame;
    }
  }
}